#!/bin/bash
set -euo pipefail
get(){
    swaymsg -pt get_outputs | grep "$1" | awk '{print $2}' || true
}
left=""
right=""

# M
left="${left}$(get J0XYN952675S)"
right="${right}$(get J0XYN8B5ADEL)"

# H
left="${left}$(get 33F2P83)"
right="${right}$(get DDYHQ83)"

swaymsg output "$left" pos 0 0
swaymsg output "$right" pos 2560 0
swaymsg output eDP-1 pos 5120 0
